from shop.models import Item, Purchase

tovar1 = Item.objects.create(name="Паук Торантул", price=100)
tovar2 = Item.objects.create(name="Паук Кристовик", price=200)
tovar3 = Item.objects.create(name="Паук Черная вдова", price=300)
tovar4 = Item.objects.create(name="Паук", price=400)
tovar5 = Item.objects.create(name="Крыса", price=500)
tovar6 = Item.objects.create(name="Кошка", price=600)
tovar7 = Item.objects.create(name="Собака", price=700)
tovar8 = Item.objects.create(name="Таракан", price=800)
tovar9 = Item.objects.create(name="Шапка", price=900)
tovar10 = Item.objects.create(name="Куртка", price=1000)


tovar1.purchases.create(name="Нурлан",age=30)
tovar2.purchases.create(name="Рустам",age=31)
tovar4.purchases.create(name="Алмаз",age=32)
tovar5.purchases.create(name="Бакыт",age=33)
tovar6.purchases.create(name="Нурсултан",age=34)
tovar7.purchases.create(name="Улук",age=35)
tovar8.purchases.create(name="Арина",age=36)
tovar9.purchases.create(name="Иман",age=37)
tovar10.purchases.create(name="Мырза",age=38)
tovar3.purchases.create(name="Мырсаид",age=39)

tovar1.purchases.all()
tovar2.purchases.all()
tovar3.purchases.all()
tovar4.purchases.all()
tovar5.purchases.all()
tovar6.purchases.all()
tovar7.purchases.all()
tovar8.purchases.all()
tovar9.purchases.all()
tovar10.purchases.all()
